# Generated by Django 5.1.6 on 2025-03-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='data',
            field=models.JSONField(default=list),
        ),
    ]
