# Generated by Django 5.1.6 on 2025-03-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_data'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['type', 'status'], name='reports_rep_type_9ff8af_idx'),
        ),
    ]
