# Generated by Django 5.1.6 on 2025-03-10 22:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasePokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('experience', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('experience_goal', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='BasePokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('pokedex_number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('base_hp', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('base_attack', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('base_defense', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('base_special_attack', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('base_special_defense', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('base_speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('types', models.ManyToManyField(related_name='base_pokemons', to='pokemons.basepokemontype')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
                ('hp', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('attack', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('defense', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('special_attack', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('special_defense', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('base_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='pokemons.basepokemon')),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to='pokemons.pokemonlevel')),
            ],
        ),
    ]
