# Generated by Django 5.1.6 on 2025-03-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='basepokemon',
            index=models.Index(fields=['name'], name='pokemons_ba_name_745923_idx'),
        ),
        migrations.AddIndex(
            model_name='basepokemon',
            index=models.Index(fields=['pokedex_number'], name='pokemons_ba_pokedex_747f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='basepokemontype',
            index=models.Index(fields=['name'], name='pokemons_ba_name_b7a8a3_idx'),
        ),
        migrations.AddIndex(
            model_name='pokemon',
            index=models.Index(fields=['nickname'], name='pokemons_po_nicknam_22116c_idx'),
        ),
    ]
