from apps.pokemons.admin.list_base_pokemon_types import list_base_pokemon_types
from apps.pokemons.admin.create_base_pokemon import create_base_pokemon
from apps.pokemons.admin.create_base_pokemon_type import create_base_pokemon_type
from apps.pokemons.admin.delete_base_pokemon_type import delete_base_pokemon_type
from apps.pokemons.admin.delete_base_pokemon import delete_base_pokemon
from apps.pokemons.admin.list_base_pokemons import list_base_pokemons
from apps.pokemons.admin.list_pokemons import list_pokemons
from apps.pokemons.admin.create_pokemon import create_pokemon
from apps.pokemons.admin.delete_pokemon import delete_pokemon
from apps.pokemons.admin.router import router